### ISSUE TITLE
congratulations

### ISSUE THREAD

**Issue by Tezcan98** [salihmarangoz/xiaomi_lds_myhome#1]
Hocam merhaba, Tebrikler küçük güzel bir çalışma olmuş. çapta bir sera robot projem var, acaba robotların lidarı böyle ortamlar için yeterli mi yoksa sadece evde mesafe ölçecek kalitede mi ?
Ayrıca lidardan veri okumak için sadece uart to USB gibi bir çevirici yeterli oluyor mu yoksa başka devreler kurdunuz mu ? Yani DC-DC dönüştürücü dışında.
teşekkürler.

**Comment by salihmarangoz** [comment]
Lidardan veri okumak icin donusturucu yeterli ama lidari belirli bir hizda dondurmek icin biraz daha karisik bir cozum (PI controller) gerekebilir. Ben sabit bir gerilim saglayarak deneyimi gerceklestirdim ama bunu yapmanizi tavsiye etmem. Bu yoldan gitmek yerine RPlidar gibi hazir urunleri tercih edebilirsiniz. Diger taraftan...

bu biraz daha ev ortami icin bir sensor. Serada calissa bile neme karsi dayanikli olmayabilir. Ben xiaomi vacuum robot yedek parcasi kullandim, ama su anda rplidar ayni seyi daha kompakt ve daha iyi yapiyor. Ancak dedigim gibi seradaki ortam sartlarinda uzun sure saglam kalir mi veya duzgun calisir mi emin degilim. Bu arada gunes isigi bu tip sensorlerin calismasini kotu etkileyebiliyor. Urunun ozelliklerini kontrol etmenizde fayda var.

Ayrica, nasil bir proje yaptiginiza gore konumlandirma yontemi degisebilir. Mesela ray uzerinde hareket eden bir robot var diyelim. Baslangic noktasina bir ip baglayip robotun uzerinde ipi gergin tutacak sekilde bir bobin olsun. Bobine bir encoder takarak da konumlandirma yapilabilir. 

Son olarak soyle bir tavsiye vereyim. Sera ortamini Gazebo'da hizlica ve kabaca tasarlayin (box, sphere gibi objelerle) ve bir robot yerlestirin. Bu sensorun menzili 5-6 metre civarinda. Simulasyondaki maksimum lidar menzilini de bu degerde ayarlayin. Eger slam/localization gayet iyi calisiyorsa o zaman gercekte de calisma ihtimali vardir. Menzili artirmaniza ragmen halen sonuc alamazsaniz 2D lidar belki de uygun bir cozum degildir.

**Comment by Tezcan98** [comment]
Cevap için teşekkürler.
RPLidar kullanmama sebebim hobi projesi için 4-5bin tl vermektense bin liralık lidarla işi çözmekdi zaten :)
ama dediğiniz gibi nem ve ışık lidarın kullanımına engel olabilir belki de evde kullanırım maksat elim alışsın :)

**Comment by salihmarangoz** [comment]
Anladim. O zaman bir adet usb-uart donusturucu ve gerilimi ayarlanabilir bir dc-dc donusturucu is gorebilir. Motor voltajini ayarlamak icin gerekli rpm degerini lidar sagliyor oradan okuyabilirsin. Normalden daha hizli veya daha yavas donmesi durumunda lidar verisinde bozulma olabiliyor.

Iyi calismalar :)
